/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        paper: "var(--text-on-accent)",
        surface: {
          DEFAULT: "var(--surface)",
          sunken: "var(--surface-sunken)",
          raised: "var(--surface-raised)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-bg)",
          surface: "var(--sidebar-surface)",
          hover: "var(--sidebar-hover)",
          active: "var(--sidebar-active)",
          text: "var(--sidebar-text)",
          "text-active": "var(--sidebar-text-active)",
        },
        ink: {
          DEFAULT: "var(--text)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          subtle: "var(--text-subtle)",
        },
        line: {
          DEFAULT: "var(--border)",
          strong: "var(--border-strong)",
          focus: "var(--border-focus)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          active: "var(--accent-active)",
          quiet: "var(--accent-quiet)",
          border: "var(--accent-border)",
          muted: "var(--accent-muted)",
        },
        ok: {
          fg: "var(--ok-fg)",
          bg: "var(--ok-bg)",
          border: "var(--ok-border)",
        },
        warn: {
          fg: "var(--warn-fg)",
          bg: "var(--warn-bg)",
          border: "var(--warn-border)",
        },
        danger: {
          fg: "var(--danger-fg)",
          bg: "var(--danger-bg)",
          border: "var(--danger-border)",
        },
      },
      fontFamily: {
        sans: [
          '"Inter"',
          '"Noto Sans Bengali"',
          "system-ui",
          "-apple-system",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "ui-monospace",
          '"SF Mono"',
          '"Cascadia Mono"',
          "Menlo",
          "Consolas",
          "monospace",
        ],
      },
      fontSize: {
        xs: ["0.75rem", "1rem"],
        sm: ["0.8125rem", "1.25rem"],
        base: ["0.875rem", "1.375rem"],
        md: ["1rem", "1.5rem"],
        lg: ["1.25rem", "1.75rem"],
        xl: ["1.5rem", "2rem"],
        "2xl": ["1.875rem", "2.25rem"],
        "3xl": ["2.25rem", "2.75rem"],
        "4xl": ["3rem", "3.5rem"],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        control: "var(--radius-control)",
        md: "var(--radius-md)",
        container: "var(--radius-container)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        overlay: "var(--shadow-overlay)",
        "card-hover": "var(--shadow-card-hover)",
      },
      spacing: {
        sidebar: "var(--sidebar-width)",
        "sidebar-collapsed": "var(--sidebar-collapsed-width)",
        topbar: "var(--topbar-height)",
      },
      maxWidth: {
        content: "var(--content-max-width)",
        form: "var(--form-max-width)",
      },
      animation: {
        "fade-in": "fadeIn 200ms ease-out both",
        "fade-in-up": "fadeInUp 300ms ease-out both",
        "fade-in-down": "fadeInDown 300ms ease-out both",
        "scale-in": "scaleIn 300ms ease-out both",
        "slide-in-left": "slideInLeft 300ms ease-out both",
        "slide-in-right": "slideInRight 300ms ease-out both",
        shimmer: "shimmer 1.5s infinite",
        float: "float 6s ease-in-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        spin: "spin 1s linear infinite",
      },
    },
  },
  plugins: [],
};
